networks:
  inside:
  outside:
services:
  caddy:
    build:
      context: /opt/dockge/caddy
      dockerfile: /opt/dockge/caddy/cloudflare.Dockerfile
    image: caddy:cloudflare
    container_name: caddy
    restart: unless-stopped
    networks:
      - outside
      - inside
    ports:
      - 9080:80
      - 9443:443
    volumes:
      - /opt/dockge/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /opt/dockge/caddy/caddy_data:/data
    environment:
      # ⚠️ You MUST set this to your dockge host's FQDN to use SSL.
      - HOST_FQDN=<host fqdn>
      # ⚠️ You MUST set this to get SSL certs from Let's Encrypt
      - HOST_EMAIL=<email>
      # ⚠️ Set this only if you are using a service which requires token authentication
      - AUTH_TOKEN=<token>
      # Registers your acceptance of the Let's Encrypt EULA and Terms of Service
      - ACME_AGREE=true
  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    depends_on:
      - caddy
    networks:
      - inside
    expose:
      - 5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/stacks/data:/app/data
      
      # If you want to use private registries, you need to share the auth file with Dockge:
      # - /root/.docker/:/root/.docker

      # Stacks Directory
      # ⚠️ READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      # ⚠️ 1. FULL path only. No relative path (MUST)
      # ⚠️ 2. Left Stacks Path === Right Stacks Path (MUST)
      - /opt/stacks:/opt/stacks
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/opt/stacks

