services:

#   noop:
#     image: padthaitofuhot/noop:running
#     networks:
#       - inside
#     restart: no

  caddy:
    build:
      context: /opt/stacks/dockge
      dockerfile: /opt/stacks/dockge/Containerfile
    image: padthaitofuhot/caddy:cloudflare
    container_name: caddy
    restart: unless-stopped
    env_file: /opt/stacks/dockge/.env
    networks:
      - outside
      - inside
    ports:
      - 80
      - 443
      - 8443
      - 9443
    volumes:
      - /opt/stacks/dockge/Caddyfile:/etc/caddy/Caddyfile
      - /opt/stacks/dockge/caddy_data:/data

  dockge:
    image: louislam/dockge:1
    container_name: dockge
    restart: unless-stopped
    env_file: /opt/stacks/dockge/.env
    networks:
      - inside
    expose:
      - 5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/stacks/dockge/dockge_data:/app/data
      - /opt/stacks:/opt/stacks
      # If you want to use private registries, you need to share the auth file with Dockge:
      #- /root/.docker/:/root/.docker

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    networks:
      - inside
    expose:
      - 8080
    volumes:
      - /opt/stacks:/srv
      - /opt/stacks/dockge/filebrowser_data/database:/database
      - /opt/stacks/dockge/filebrowser_data/.filebrowser.json:/.filebrowser.json

networks:
  inside:
  outside: