FROM docker.io/library/caddy:builder AS cb
RUN caddy-builder \
    github.com/caddy-dns/cloudflare \
    github.com/caddyserver/transform-encoder
FROM docker.io/library/caddy:latest
COPY --from=cb /usr/bin/caddy /usr/bin/caddy
RUN apk update \
    && apk upgrade \
    && apk add nss-tools
